"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Copy, Download, ExternalLink, ImageIcon, Search, Share2, Sparkles } from "lucide-react";

type ProductImage={id:string;url:string};
type Product={id:string;name:string;brand:string;price:number;promoPrice:number|null;stockQty:number;active:boolean;featured:boolean;isNew:boolean;bestSeller:boolean;createdAt:string;imageUrl:string|null;images:ProductImage[];category:{name:string}};
type Branding={storeName:string;logoUrl:string|null};
type Format="status"|"quadrado"; type Template="preco"|"oferta"|"novidade"; type Strategy="beneficio"|"dor_solucao"|"curiosidade";
type Variation={strategy:Strategy;hook:string;support:string};
const DEEP="#8D4F5F",ROSE="#B25573",DARK="#2F2529",CREAM="#FFF8FA",PINK="#F4D9DF",GOLD="#D4AF37";
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const promo=(p:Product)=>p.promoPrice!==null&&p.promoPrice<p.price;
const templateFor=(p:Product):Template=>promo(p)?"oferta":p.isNew?"novidade":"preco";
const label=(t:Template)=>t==="oferta"?"OFERTA":t==="novidade"?"NOVIDADE":"DESTAQUE";
const fallback=(p:Product,t:Template)=>t==="oferta"?{hook:"PREÇO ESPECIAL",support:"Seu favorito com uma condição que merece destaque."}:t==="novidade"?{hook:"CHEGOU NA SRA MAKE",support:"Uma novidade para conhecer e incluir na sua rotina."}:{hook:p.bestSeller?"UM DOS DESTAQUES DA SRA MAKE":"ESCOLHA DA SRA MAKE",support:"Produto, preço e compra fácil direto pelo catálogo."};
function load(src:string){return new Promise<HTMLImageElement>((ok,no)=>{const i=new Image();i.crossOrigin="anonymous";i.onload=()=>ok(i);i.onerror=no;i.src=src})}
function rr(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){c.beginPath();c.roundRect(x,y,w,h,r)}
function cover(c:CanvasRenderingContext2D,i:HTMLImageElement,x:number,y:number,w:number,h:number){const s=Math.max(w/i.width,h/i.height),dw=i.width*s,dh=i.height*s;c.drawImage(i,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function lines(c:CanvasRenderingContext2D,t:string,w:number,n:number){const a=t.replace(/[\*_~#]/g,"").split(/\s+/),out:string[]=[];let q="";for(const z of a){const k=q?`${q} ${z}`:z;if(c.measureText(k).width>w&&q){out.push(q);q=z;if(out.length===n-1)break}else q=k}if(q&&out.length<n)out.push(q);return out}
function priceParts(v:number){const s=v.toFixed(2).replace(".",",");const [a,b]=s.split(",");return {a,b}}
function drawPrice(c:CanvasRenderingContext2D,v:number,x:number,y:number,maxW:number,large:boolean){const {a,b}=priceParts(v);c.textAlign="left";c.fillStyle=DEEP;c.font=`800 ${large?52:38}px Arial`;c.fillText("R$",x,y);const rx=x+(large?78:58);c.font=`900 ${large?126:88}px Arial`;const main=`${a},`;c.fillText(main,rx,y+10);const mw=c.measureText(main).width;c.font=`900 ${large?62:44}px Arial`;c.fillText(b,Math.min(rx+mw, x+maxW-80),y-22)}
async function draw(canvas:HTMLCanvasElement,p:Product,img:string|null,format:Format,t:Template,branding:Branding,copy:{hook:string;support:string}){const w=1080,h=format==="status"?1920:1080;canvas.width=w;canvas.height=h;const c=canvas.getContext("2d");if(!c)return;let image:HTMLImageElement|null=null;if(img)try{image=await load(img)}catch{}
 c.fillStyle=CREAM;c.fillRect(0,0,w,h);const m=format==="status"?64:50;
 // faixa de marca: fixa e limpa
 c.fillStyle=DEEP;c.fillRect(0,0,w,format==="status"?138:104);c.fillStyle="#fff";c.textAlign="left";c.font=`700 ${format==="status"?46:34}px Georgia`;c.fillText(branding.storeName||"Sra Make Prudente",m,format==="status"?88:67);
 // selo comercial de alto contraste
 const bw=format==="status"?250:205,bh=format==="status"?82:64,bx=w-m-bw,by=format==="status"?172:130;rr(c,bx,by,bw,bh,18);c.fillStyle=t==="novidade"?DARK:t==="oferta"?ROSE:GOLD;c.fill();c.fillStyle="#fff";c.textAlign="center";c.font=`900 ${format==="status"?31:24}px Arial`;c.fillText(label(t),bx+bw/2,by+(format==="status"?53:42));
 // headline curta, não compete com preço
 c.textAlign="left";c.fillStyle=DARK;c.font=`900 ${format==="status"?55:39}px Arial`;const hs=lines(c,copy.hook.toUpperCase(),format==="status"?w-m*2-bw-20:w-m*2-bw-15,2);const hy=format==="status"?210:158;hs.forEach((s,i)=>c.fillText(s,m,hy+i*(format==="status"?61:44)));
 // fotografia: maior elemento da peça
 const iy=format==="status"?330:235,ih=format==="status"?930:545,iw=w-m*2;rr(c,m,iy,iw,ih,30);c.fillStyle="#fff";c.fill();c.save();rr(c,m,iy,iw,ih,30);c.clip();if(image)cover(c,image,m,iy,iw,ih);else{c.fillStyle=PINK;c.fillRect(m,iy,iw,ih);c.fillStyle=DEEP;c.textAlign="center";c.font="700 34px Arial";c.fillText("FOTO DO PRODUTO",w/2,iy+ih/2)}c.restore();
 if(format==="quadrado"){
   // rodapé comercial para feed: nome + preço lado a lado
   const base=810;c.textAlign="left";c.fillStyle=DARK;c.font="700 37px Georgia";const ns=lines(c,p.name,560,2);ns.forEach((s,i)=>c.fillText(s,m,base+i*43));if(promo(p)){c.fillStyle="#766A6F";c.font="500 20px Arial";c.fillText(`DE ${money(p.price)}`,650,base-18)}drawPrice(c,p.promoPrice??p.price,650,base+55,370,false);
   c.fillStyle=DEEP;c.fillRect(0,990,w,90);c.fillStyle="#fff";c.textAlign="center";c.font="800 27px Arial";c.fillText("COMPRE PELO CATÁLOGO  →",w/2,1047);return;
 }
 // status: produto + argumento + bloco de preço com regra visual rígida
 let ty=1345;c.textAlign="left";c.fillStyle=DARK;c.font="700 54px Georgia";const ns=lines(c,p.name,w-m*2,2);ns.forEach((s,i)=>c.fillText(s,m,ty+i*62));ty+=ns.length*62+18;
 if(p.brand&&!norm(p.name).includes(norm(p.brand))){c.fillStyle=ROSE;c.font="700 27px Arial";c.fillText(p.brand,m,ty);ty+=42}
 c.fillStyle="#5F5358";c.font="500 27px Arial";const ss=lines(c,copy.support,w-m*2,2);ss.forEach((s,i)=>c.fillText(s,m,ty+i*37));
 const py=1640;if(promo(p)){c.fillStyle="#6F6368";c.font="600 27px Arial";c.fillText(`DE ${money(p.price)}`,m,py-55);c.strokeStyle=ROSE;c.lineWidth=3;c.beginPath();c.moveTo(m,py-66);c.lineTo(m+185,py-66);c.stroke()}
 rr(c,m,py-25,570,175,28);c.fillStyle="#fff";c.fill();drawPrice(c,p.promoPrice??p.price,m+28,py+72,510,true);
 c.fillStyle=DEEP;c.fillRect(0,h-130,w,130);c.fillStyle="#fff";c.textAlign="center";c.font="900 32px Arial";c.fillText("COMPRE PELO CATÁLOGO  →",w/2,h-76);c.font="500 20px Arial";c.fillText("Sra Make Prudente · Retirada ou entrega em Presidente Prudente",w/2,h-38)}
function shortUrl(site:string,p:Product,format:Format,source:"social"|"whatsapp"|"instagram"){const s=source==="whatsapp"?"w":source==="instagram"?"i":"s";return `${site.replace(/\/$/,"")}/r/${p.id.slice(-7)}?f=${format==="status"?"s":"q"}&s=${s}`}
function message(p:Product,url:string,copy:{hook:string;support:string}){return [`✨ *${copy.hook}*`,`💗 *${p.name}*${p.brand&&!norm(p.name).includes(norm(p.brand))?`\n${p.brand}`:""}`,copy.support,promo(p)?`✨ ~De ${money(p.price)}~ por *${money(p.promoPrice!)}*`:`✨ *${money(p.price)}*`,`🛍️ *Compre pelo catálogo:*\n${url}`,"📍 Retirada ou entrega em Presidente Prudente."].join("\n\n")}
export function PromotionCenterV4({products,branding,siteUrl="https://sramakeprudente.com.br"}:{products:Product[];branding:Branding;siteUrl?:string}){const available=useMemo(()=>products.filter(p=>p.active&&p.stockQty>0),[products]);const [id,setId]=useState(available[0]?.id||"");const [query,setQuery]=useState("");const [format,setFormat]=useState<Format>("status");const [template,setTemplate]=useState<Template>(available[0]?templateFor(available[0]):"preco");const [img,setImg]=useState<string|null>(available[0]?.images[0]?.url??null);const [variation,setVariation]=useState<Variation|null>(null);const [vars,setVars]=useState<Variation[]>([]);const [loading,setLoading]=useState(false);const [note,setNote]=useState("");const canvas=useRef<HTMLCanvasElement>(null);const p=available.find(x=>x.id===id)||available[0];const filtered=available.filter(x=>norm(`${x.name} ${x.brand}`).includes(norm(query)));const copy=variation??fallback(p,template);const text=message(p,shortUrl(siteUrl,p,format,"social"),copy);
 useEffect(()=>{if(!p)return;setImg(p.images[0]?.url??p.imageUrl);setTemplate(templateFor(p));setVariation(null);setVars([])},[p?.id]);useEffect(()=>{if(canvas.current&&p)draw(canvas.current,p,img,format,template,branding,copy)},[p,img,format,template,branding,copy.hook,copy.support]);
 async function ai(){setLoading(true);setNote("");try{const r=await fetch("/api/admin/ai/promotion-copy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:p.id})});const d=await r.json();if(!r.ok||!Array.isArray(d.variations))throw new Error(d.error||"Falha ao gerar copy");setVars(d.variations);setVariation(d.variations[0])}catch(e){setNote(e instanceof Error?e.message:"Falha ao gerar copy")}finally{setLoading(false)}}
 async function blob(){return new Promise<Blob|null>(r=>{if(!canvas.current)return r(null);canvas.current.toBlob(r,"image/png",.96)})}async function download(){const b=await blob();if(!b)return;const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`sra-make-${p.id.slice(-7)}-${template}-${format}.png`;a.click();URL.revokeObjectURL(u)}async function copyText(){await navigator.clipboard.writeText(text);setNote("Legenda e link copiados.")}function whats(){window.open(`https://wa.me/?text=${encodeURIComponent(message(p,shortUrl(siteUrl,p,format,"whatsapp"),copy))}`,"_blank")}
 async function share(){const b=await blob();if(!b)return;const caption=message(p,shortUrl(siteUrl,p,format,"instagram"),copy);await navigator.clipboard.writeText(caption).catch(()=>{});const f=new File([b],`sra-make-${p.id.slice(-7)}.png`,{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[f]})){try{await navigator.share({files:[f],text:caption,title:p.name})}catch{}setNote("Arte compartilhada. Legenda e link copiados para colar no Instagram.")}else{await download();setNote("Arte salva. Legenda e link copiados.")}}
 if(!p)return <div className="rounded-2xl bg-white p-5">Nenhum produto disponível.</div>;
 return <div className="space-y-5"><section className="rounded-2xl border border-rosa/15 bg-white p-5"><div className="flex gap-3"><Sparkles className="text-rosa-profundo"/><div><h2 className="font-serif text-xl font-bold">Central de Divulgação V4</h2><p className="text-sm text-cinza">Templates comerciais fixos: produto, preço e CTA sempre em destaque.</p></div></div><div className="mt-4 relative"><Search className="absolute left-3 top-3 text-cinza" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto..." className="w-full rounded-xl border border-rosa/20 py-2.5 pl-9 pr-3 text-sm"/></div><select value={p.id} onChange={e=>setId(e.target.value)} className="mt-2 w-full rounded-xl border border-rosa/20 p-3 text-sm">{filtered.map(x=><option key={x.id} value={x.id}>{x.name} — {x.brand}</option>)}</select></section>
 <section className="rounded-2xl border border-rosa/15 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-serif text-lg font-bold">Arte comercial</h2><p className="text-sm text-cinza">O template troca os dados; a hierarquia profissional permanece.</p></div><div className="flex flex-wrap gap-2">{(["preco","oferta","novidade"] as Template[]).map(x=><button key={x} onClick={()=>setTemplate(x)} className={`rounded-lg px-3 py-2 text-xs font-bold ${template===x?"bg-rosa-profundo text-white":"border border-rosa/20"}`}>{x==="preco"?"Preço Forte":x==="oferta"?"Oferta":"Novidade"}</button>)}{(["status","quadrado"] as Format[]).map(x=><button key={x} onClick={()=>setFormat(x)} className={`rounded-lg px-3 py-2 text-xs font-bold ${format===x?"bg-texto text-white":"border border-rosa/20"}`}>{x==="status"?"9:16":"1:1"}</button>)}</div></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[430px_1fr]"><div><div className="rounded-2xl bg-creme p-3"><canvas ref={canvas} className="w-full rounded-xl"/></div>{p.images.length>1&&<div className="mt-3 flex gap-2 overflow-x-auto">{p.images.map((x,i)=><button key={x.id} onClick={()=>setImg(x.url)} className={`h-20 w-20 shrink-0 rounded-xl border-2 bg-contain bg-center bg-no-repeat ${img===x.url?"border-rosa-profundo":"border-rosa/15"}`} style={{backgroundImage:`url(${x.url})`}} aria-label={`Foto ${i+1}`}/>)}</div>}</div>
 <div className="space-y-3"><div className="rounded-xl border border-rosa/15 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold">Direção de copy</p><p className="text-xs text-cinza">A IA escreve; o template controla a hierarquia visual.</p></div><button onClick={ai} disabled={loading} className="rounded-lg bg-rosa-profundo px-3 py-2 text-xs font-bold text-white">{loading?"Gerando...":"Gerar 3 com IA"}</button></div>{vars.length>0&&<div className="mt-3 grid gap-2">{vars.map((v,i)=><button key={i} onClick={()=>setVariation(v)} className={`rounded-xl border p-3 text-left ${variation===v?"border-rosa-profundo bg-rosa-claro/20":"border-rosa/15"}`}><b>{v.hook}</b><div className="mt-1 text-xs text-cinza">{v.support}</div></button>)}</div>}</div>
 <div className="rounded-xl bg-rosa-claro/20 p-4 whitespace-pre-wrap text-sm leading-6">{text}</div><button onClick={whats} className="flex w-full items-center justify-center gap-2 rounded-xl bg-rosa-profundo px-4 py-3 font-bold text-white"><ExternalLink size={17}/>WhatsApp</button><button onClick={share} className="flex w-full items-center justify-center gap-2 rounded-xl border border-rosa/20 px-4 py-3 font-bold text-rosa-profundo"><Share2 size={17}/>Instagram / Compartilhar</button><div className="grid grid-cols-2 gap-2"><button onClick={copyText} className="flex items-center justify-center gap-2 rounded-xl border border-rosa/20 px-3 py-3 font-bold"><Copy size={16}/>Copiar legenda</button><button onClick={download} className="flex items-center justify-center gap-2 rounded-xl border border-rosa/20 px-3 py-3 font-bold"><Download size={16}/>Baixar arte</button></div>{note&&<p className="rounded-lg bg-blue-50 p-3 text-xs text-blue-700">{note}</p>}</div></div></section>
 <section className="rounded-2xl border border-rosa/15 bg-white p-5"><div className="flex items-center gap-2"><ImageIcon className="text-rosa-profundo" size={18}/><b>Regra visual V4</b></div><p className="mt-2 text-sm text-cinza">Preço nunca vira texto secundário. Em oferta, DE/POR recebe hierarquia própria. Foto ocupa a maior área útil e o CTA permanece fixo.</p></section></div>}
