"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Copy, Download, ExternalLink, ImageIcon, Search, Share2, Sparkles } from "lucide-react";

type ProductImage={id:string;url:string};
type Product={id:string;name:string;brand:string;price:number;promoPrice:number|null;stockQty:number;active:boolean;featured:boolean;isNew:boolean;bestSeller:boolean;createdAt:string;imageUrl:string|null;images:ProductImage[];category:{name:string}};
type Branding={storeName:string;logoUrl:string|null};
type Format="status"|"quadrado"; type Layout="editorial"|"hero"|"oferta"; type Strategy="beneficio"|"dor_solucao"|"curiosidade";
type Variation={strategy:Strategy;hook:string;support:string};
const ROSE="#B25573",DEEP="#8D4F5F",DARK="#372D31",CREAM="#FFF8FA";
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const promo=(p:Product)=>p.promoPrice!==null&&p.promoPrice<p.price;
const kind=(p:Product)=>promo(p)?"OFERTA":p.isNew?"NOVIDADE":p.bestSeller?"MAIS PEDIDO":"DESTAQUE";
const family=(p:Product)=>{const s=norm(`${p.category.name} ${p.name}`);if(/body|perfume|colonia|splash|fragr/.test(s))return"Perfumaria";if(/cabelo|touca|escova|pente|capilar/.test(s))return"Cabelo";if(/pin[cç]a|esponja|aplicador|acessor/.test(s))return"Acessórios";return"Maquiagem"};
const fallback=(p:Product)=>family(p)==="Perfumaria"?{hook:"UM TOQUE DE PERFUME PARA A SUA ROTINA",support:"Conheça a fragrância e escolha a sua favorita."}:family(p)==="Cabelo"?{hook:"CUIDADO QUE FAZ PARTE DA ROTINA",support:"Praticidade para cuidar dos fios no dia a dia."}:family(p)==="Acessórios"?{hook:"DETALHES QUE FACILITAM SUA ROTINA",support:"Um aliado prático para completar seus cuidados."}:{hook:"SEU NOVO DESTAQUE DE BELEZA",support:"Conheça os detalhes e encontre seu próximo favorito."};
function load(src:string){return new Promise<HTMLImageElement>((ok,no)=>{const i=new Image();i.crossOrigin="anonymous";i.onload=()=>ok(i);i.onerror=no;i.src=src})}
function rr(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){c.beginPath();c.roundRect(x,y,w,h,r)}
function cover(c:CanvasRenderingContext2D,i:HTMLImageElement,x:number,y:number,w:number,h:number){const s=Math.max(w/i.width,h/i.height),dw=i.width*s,dh=i.height*s;c.drawImage(i,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function lines(c:CanvasRenderingContext2D,t:string,w:number,n:number){const a=t.replace(/[\*_~#]/g,"").split(/\s+/),out:string[]=[];let q="";for(const z of a){const k=q?`${q} ${z}`:z;if(c.measureText(k).width>w&&q){out.push(q);q=z;if(out.length===n-1)break}else q=k}if(q&&out.length<n)out.push(q);return out}
function accentFromImage(i:HTMLImageElement){const cv=document.createElement("canvas");cv.width=cv.height=48;const c=cv.getContext("2d")!;c.drawImage(i,0,0,48,48);const d=c.getImageData(0,0,48,48).data;let best=[151,88,139],score=-1;for(let x=0;x<d.length;x+=16){const r=d[x],g=d[x+1],b=d[x+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx-mn,lum=(r+g+b)/3;if(lum<45||lum>225||sat<28)continue;const sc=sat-Math.abs(lum-145)*.25;if(sc>score){score=sc;best=[r,g,b]}}return `rgb(${best[0]},${best[1]},${best[2]})`}
async function draw(canvas:HTMLCanvasElement,p:Product,img:string|null,format:Format,layout:Layout,branding:Branding,copy:{hook:string;support:string}){const w=1080,h=format==="status"?1920:1080;canvas.width=w;canvas.height=h;const c=canvas.getContext("2d");if(!c)return;let image:HTMLImageElement|null=null,accent="#9560A8";if(img)try{image=await load(img);accent=accentFromImage(image)}catch{}
 const bg=c.createLinearGradient(0,0,w,h);bg.addColorStop(0,CREAM);bg.addColorStop(.58,"#F8E5E9");bg.addColorStop(1,"#EBC5CE");c.fillStyle=bg;c.fillRect(0,0,w,h);c.globalAlpha=.13;c.fillStyle=accent;c.beginPath();c.arc(w-80,240,310,0,Math.PI*2);c.fill();c.beginPath();c.arc(70,h-270,260,0,Math.PI*2);c.fill();c.globalAlpha=1;
 const m=format==="status"?58:48;c.fillStyle=DEEP;c.font=`700 ${format==="status"?48:38}px Georgia`;c.textAlign="left";c.fillText(branding.storeName||"Sra Make Prudente",m,92);rr(c,w-m-220,40,220,74,26);c.fillStyle=accent;c.fill();c.fillStyle="#fff";c.font=`700 ${format==="status"?27:23}px Arial`;c.textAlign="center";c.fillText(kind(p),w-m-110,88);
 const hook=copy.hook.toUpperCase();c.textAlign="left";c.fillStyle=ROSE;c.font=`700 ${format==="status"?47:36}px Arial`;const hs=lines(c,hook,w-m*2,2);hs.forEach((t,i)=>c.fillText(t,m,185+i*(format==="status"?55:43)));
 let ix=m,iy=format==="status"?300:215,iw=w-m*2,ih=format==="status"?900:520;if(format==="quadrado"&&layout==="editorial"){iw=555;ih=610}if(format==="status"&&layout==="hero"){iy=275;ih=1040}rr(c,ix,iy,iw,ih,layout==="editorial"?12:34);c.fillStyle="#fff";c.fill();c.save();rr(c,ix,iy,iw,ih,layout==="editorial"?12:34);c.clip();if(image)cover(c,image,ix,iy,iw,ih);c.restore();
 const tx=format==="quadrado"&&layout==="editorial"?640:m;let ty=format==="quadrado"&&layout==="editorial"?275:iy+ih+70;const tw=w-tx-m;c.fillStyle=DARK;c.font=`700 ${format==="status"?58:40}px Georgia`;const ns=lines(c,p.name,tw,format==="status"?2:3);ns.forEach((t,i)=>c.fillText(t,tx,ty+i*(format==="status"?67:47)));ty+=ns.length*(format==="status"?67:47)+12;
 if(p.brand&&!norm(p.name).includes(norm(p.brand))){c.fillStyle=accent;c.font=`700 ${format==="status"?28:22}px Arial`;c.fillText(p.brand,tx,ty);ty+=format==="status"?48:36}
 c.fillStyle=DARK;c.font=`500 ${format==="status"?29:22}px Arial`;const ss=lines(c,copy.support,tw,2);ss.forEach((t,i)=>c.fillText(t,tx,ty+i*(format==="status"?40:30)));ty+=ss.length*(format==="status"?40:30)+28;
 if(promo(p)){c.fillStyle="#7B7074";c.font=`500 ${format==="status"?27:20}px Arial`;c.fillText(`de ${money(p.price)}`,tx,ty);ty+=38}
 c.fillStyle=accent;c.font=`700 ${format==="status"?70:50}px Arial`;c.fillText(money(p.promoPrice??p.price),tx,ty+58);
 const fy=h-(format==="status"?155:92);c.fillStyle=DEEP;c.fillRect(0,fy,w,h-fy);c.fillStyle="#fff";c.textAlign="center";c.font=`700 ${format==="status"?34:25}px Arial`;c.fillText("CONHEÇA NO CATÁLOGO  →",w/2,fy+(format==="status"?62:39));c.font=`500 ${format==="status"?23:17}px Arial`;c.fillText("Sra Make Prudente · Presidente Prudente/SP",w/2,fy+(format==="status"?105:68));}
function shortUrl(site:string,p:Product,format:Format,source:"social"|"whatsapp"|"instagram"){const s=source==="whatsapp"?"w":source==="instagram"?"i":"s";return `${site.replace(/\/$/,"")}/r/${p.id.slice(-7)}?f=${format==="status"?"s":"q"}&s=${s}`}
function message(p:Product,url:string,copy:{hook:string;support:string}){return [`✨ *${copy.hook}*`,`💗 *${p.name}*${p.brand&&!norm(p.name).includes(norm(p.brand))?`\n${p.brand}`:""}`,copy.support,promo(p)?`✨ ~De ${money(p.price)}~ por *${money(p.promoPrice!)}*`:`✨ *${money(p.price)}*`,`🛍️ *Conheça no catálogo:*\n${url}`,"📍 Retirada ou entrega em Presidente Prudente."].join("\n\n")}
export function PromotionCenterV3({products,branding,siteUrl="https://sramakeprudente.com.br"}:{products:Product[];branding:Branding;siteUrl?:string}){const available=useMemo(()=>products.filter(p=>p.active&&p.stockQty>0),[products]);const [id,setId]=useState(available[0]?.id||"");const [query,setQuery]=useState("");const [format,setFormat]=useState<Format>("status");const [layout,setLayout]=useState<Layout>("editorial");const [img,setImg]=useState<string|null>(available[0]?.images[0]?.url??null);const [variation,setVariation]=useState<Variation|null>(null);const [vars,setVars]=useState<Variation[]>([]);const [loading,setLoading]=useState(false);const [note,setNote]=useState("");const canvas=useRef<HTMLCanvasElement>(null);const p=available.find(x=>x.id===id)||available[0];const filtered=available.filter(x=>norm(`${x.name} ${x.brand}`).includes(norm(query)));const copy=variation??fallback(p);const url=shortUrl(siteUrl,p,format,"social");const text=message(p,url,copy);
 useEffect(()=>{if(!p)return;setImg(p.images[0]?.url??p.imageUrl);setVariation(null);setVars([])},[p?.id]);useEffect(()=>{if(canvas.current&&p)draw(canvas.current,p,img,format,layout,branding,copy)},[p,img,format,layout,branding,copy.hook,copy.support]);
 async function ai(){setLoading(true);setNote("");try{const r=await fetch("/api/admin/ai/promotion-copy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:p.id})});const d=await r.json();if(!r.ok||!Array.isArray(d.variations))throw new Error(d.error||"Falha ao gerar copy");setVars(d.variations);setVariation(d.variations[0])}catch(e){setNote(e instanceof Error?e.message:"Falha ao gerar copy")}finally{setLoading(false)}}
 async function blob(){return new Promise<Blob|null>(r=>canvas.current?.toBlob(r,"image/png",.95)??r(null))}async function download(){const b=await blob();if(!b)return;const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`sra-make-${p.id.slice(-7)}-${format}.png`;a.click();URL.revokeObjectURL(u)}async function copyText(){await navigator.clipboard.writeText(text);setNote("Legenda e link copiados.")}function whats(){const t=message(p,shortUrl(siteUrl,p,format,"whatsapp"),copy);window.open(`https://wa.me/?text=${encodeURIComponent(t)}`,"_blank")}
 async function share(){const b=await blob();if(!b)return;const caption=message(p,shortUrl(siteUrl,p,format,"instagram"),copy);await navigator.clipboard.writeText(caption).catch(()=>{});const f=new File([b],`sra-make-${p.id.slice(-7)}.png`,{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[f]})){try{await navigator.share({files:[f],text:caption,title:p.name})}catch{}setNote("Arte compartilhada. A legenda e o link ficaram copiados para colar no Instagram.")}else{await download();setNote("Arte salva. A legenda e o link ficaram copiados.")}}
 if(!p)return <div className="rounded-2xl bg-white p-5">Nenhum produto disponível.</div>;
 return <div className="space-y-5"><section className="rounded-2xl border border-rosa/15 bg-white p-5"><div className="flex gap-3"><Sparkles className="text-rosa-profundo"/><div><h2 className="font-serif text-xl font-bold">Direção Criativa V3</h2><p className="text-sm text-cinza">Identidade Sra Make + cor do produto + copy estratégica.</p></div></div><div className="mt-4 relative"><Search className="absolute left-3 top-3 text-cinza" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto..." className="w-full rounded-xl border border-rosa/20 py-2.5 pl-9 pr-3 text-sm"/></div><select value={p.id} onChange={e=>setId(e.target.value)} className="mt-2 w-full rounded-xl border border-rosa/20 p-3 text-sm">{filtered.map(x=><option key={x.id} value={x.id}>{x.name} — {x.brand}</option>)}</select></section>
 <section className="rounded-2xl border border-rosa/15 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-serif text-lg font-bold">Campanha pronta</h2><p className="text-sm text-cinza">{family(p)} · paleta adaptativa extraída da foto.</p></div><div className="flex flex-wrap gap-2">{(["editorial","hero","oferta"] as Layout[]).map(x=><button key={x} onClick={()=>setLayout(x)} className={`rounded-lg px-3 py-2 text-xs font-bold ${layout===x?"bg-rosa-profundo text-white":"border border-rosa/20"}`}>{x==="editorial"?"Editorial":x==="hero"?"Produto Hero":"Oferta"}</button>)}{(["status","quadrado"] as Format[]).map(x=><button key={x} onClick={()=>setFormat(x)} className={`rounded-lg px-3 py-2 text-xs font-bold ${format===x?"bg-texto text-white":"border border-rosa/20"}`}>{x==="status"?"9:16":"1:1"}</button>)}</div></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[430px_1fr]"><div><div className="rounded-2xl bg-creme p-3"><canvas ref={canvas} className="w-full rounded-xl"/></div>{p.images.length>1&&<div className="mt-3 flex gap-2 overflow-x-auto">{p.images.map((x,i)=><button key={x.id} onClick={()=>setImg(x.url)} className={`h-20 w-20 shrink-0 rounded-xl border-2 bg-contain bg-center bg-no-repeat ${img===x.url?"border-rosa-profundo":"border-rosa/15"}`} style={{backgroundImage:`url(${x.url})`}} aria-label={`Foto ${i+1}`}/>)}</div>}</div>
 <div className="space-y-3"><div className="rounded-xl border border-rosa/15 p-4"><div className="flex items-center justify-between"><div><p className="font-bold text-sm">Direção de copy</p><p className="text-xs text-cinza">A mesma ideia alimenta a arte e a legenda.</p></div><button onClick={ai} disabled={loading} className="rounded-lg bg-rosa-profundo px-3 py-2 text-xs font-bold text-white">{loading?"Criando...":"Gerar 3 com IA"}</button></div>{vars.length>0&&<div className="mt-3 space-y-2">{vars.map((v,i)=><button key={i} onClick={()=>setVariation(v)} className={`w-full rounded-xl border p-3 text-left ${variation===v?"border-rosa-profundo bg-rosa/5":"border-rosa/15"}`}><span className="text-[10px] font-bold uppercase text-rosa-profundo">{v.strategy.replace("_"," / ")}</span><p className="font-bold text-sm">{v.hook}</p><p className="text-xs text-cinza">{v.support}</p></button>)}</div>}</div><div className="rounded-xl bg-creme p-4 whitespace-pre-wrap text-sm leading-6">{text}</div><button onClick={whats} className="flex w-full items-center justify-center gap-2 rounded-xl bg-rosa-profundo p-3 font-bold text-white"><ExternalLink size={16}/> WhatsApp</button><button onClick={share} className="flex w-full items-center justify-center gap-2 rounded-xl border border-rosa/20 p-3 font-bold text-rosa-profundo"><Share2 size={16}/> Instagram / Compartilhar</button><div className="grid grid-cols-2 gap-2"><button onClick={copyText} className="flex items-center justify-center gap-2 rounded-xl border p-3 text-sm font-bold"><Copy size={15}/> Copiar legenda</button><button onClick={download} className="flex items-center justify-center gap-2 rounded-xl border p-3 text-sm font-bold"><Download size={15}/> Baixar arte</button></div>{note&&<p className="rounded-xl bg-creme p-3 text-xs text-cinza">{note}</p>}</div></div></section></div>}
