ALTER TABLE "StoreSettings"
  ADD COLUMN IF NOT EXISTS "homeHiddenOffers" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "homeHiddenFeatured" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "homeHiddenPopular" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "homeHiddenNew" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
